# -*- coding: utf-8 -*-
"""mordred_qm9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TH7izdCKsATKsXxoqRhu8fpvu44il48
"""

import zipfile

with zipfile.ZipFile('all_desc_qm9.zip', 'r') as zip_ref:
    zip_ref.extractall('')

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("all_desc_qm9.csv")

df.head()

df.info()

df.columns

df.drop(['Unnamed: 0'], axis=1, inplace=True)

df.head()

df_valid = df.describe()

df_valid.columns

df_usable = df[df_valid.columns]
df_usable.head()

df_usable.to_csv("desc_mordred_qm9.csv")

